import os
import std/strformat
import json

const EXTENSION_PATH = "\\Documents\\CopperCube\\extensions"

proc createExtension*(itemsString: string, friendlyName: string, extensionPostfix: string): string =
    let extensionName = fmt"action_Vars_{extensionPostfix}"
    let extensionText = fmt"""
    // This extension is generated by CopperCube Variable editor
    /*
        <action jsname="{extensionName}" description={friendlyName.escapeJson()}>
        </action>
    */
    {extensionName} = function () {{}}
    {extensionName}.prototype.execute = function (node) {{
    {itemsString}
    }}
    """
    let outputPath = getEnv("USERPROFILE") & EXTENSION_PATH & "\\action_Vars_" & extensionPostfix & ".js"
    echo fmt"Extension exported to {outputPath}"
    writeFile(outputPath, extensionText)

    return outputPath