import os
import std/strformat
import json

const PLUGIN_FILENAME = "\\Documents\\CopperCube\\plugins\\start_cve.js"

proc createPlugin*() =
    let pluginText = fmt"""
    // This plugin is generated by CopperCube variable manager.
    // You probably should not edit it.
    // If it doesn't work try generating it again using the app itself, or contact Okeoke through
    // forum or discord
    function startCVE() {{
        system('start "" {getAppFilename().escapeJson()}', false);
    }}
    editorRegisterMenuEntry("startCVE()", "Start CVE\tCtrl+D");
    """
    let outputPath = getEnv("USERPROFILE") & PLUGIN_FILENAME
    echo fmt"Plugin exported to {outputPath}"
    writeFile(outputPath, pluginText)
